FROM java:8
VOLUME /java
ARG finalName
ADD $finalName /tryPolicy.jar
ENTRYPOINT ["java","-Djavax.net.ssl.trustStore=/java/keystore/mhc.keystore","-Djavax.net.ssl.trustStorePassword=changeit","-jar","/tryPolicy.jar","--spring.profiles.active=docker"]